version: '3.8'

services:
  testserver:
    build: .
    ports:
      - "8124:8124"  # Stats server port
      - "8125:8125"  # Play-by-play server port
    environment:
      - PLAYBYPLAY_PORT=8125
      - STATS_PORT=8124
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8125/v1/gamecenter/test/play-by-play"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

networks:
  default:
    name: testserver-network
